const products = [
  {id:'sunflower',name:'دوار الشمس',type:'جوزي ومقرمش',price:75,tag:'popular',badge:'الأكثر طلبًا',image:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=700&q=80'},
  {id:'radish',name:'الفجل الأحمر',type:'نكهة فلفلية منعشة',price:85,tag:'spicy',badge:'حصاد اليوم',image:'https://images.unsplash.com/photo-1591375275624-cd8aeff15c5f?auto=format&fit=crop&w=700&q=80'},
  {id:'broccoli',name:'بروكلي',type:'خفيف وطازج يوميًا',price:80,tag:'mild',badge:'غني بالمغذيات',image:'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=700&q=80'},
  {id:'arugula',name:'جرجير',type:'فلفلي بلمسة جوزية',price:85,tag:'spicy',badge:'للبيتزا والسلطات',image:'https://images.unsplash.com/photo-1557844352-761f2565b576?auto=format&fit=crop&w=700&q=80'},
  {id:'pea',name:'براعم البازلاء',type:'حلوة ومقرمشة',price:70,tag:'mild',badge:'للأطفال',image:'https://images.unsplash.com/photo-1599599810694-57a6b6bba5a7?auto=format&fit=crop&w=700&q=80'},
  {id:'red-cabbage',name:'كرنب أحمر',type:'قوام ناعم ولون مبهج',price:80,tag:'colorful',badge:'لون طبيعي',image:'https://images.unsplash.com/photo-1594282486552-05ccc30f71c0?auto=format&fit=crop&w=700&q=80'},
  {id:'kale',name:'كيل روسي',type:'ترابي وخفيف',price:85,tag:'mild',badge:'سوبر فود',image:'https://images.unsplash.com/photo-1515543904379-3d757afe72e2?auto=format&fit=crop&w=700&q=80'},
  {id:'mustard',name:'خردل أحمر',type:'دفعة حارة للشيف',price:80,tag:'spicy',badge:'جديد',image:'https://images.unsplash.com/photo-1518176258769-f227c798150e?auto=format&fit=crop&w=700&q=80'},
  {id:'kohlrabi',name:'كولرابي بنفسجي',type:'هشّ وحلو قليلًا',price:90,tag:'colorful',badge:'موسمي',image:'https://images.unsplash.com/photo-1598330822379-7d41a4c8f10b?auto=format&fit=crop&w=700&q=80'},
  {id:'basil',name:'ريحان إيطالي',type:'رائحة إيطالية مركزة',price:105,tag:'aromatic',badge:'للباستا',image:'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=700&q=80'},
  {id:'cilantro',name:'كزبرة',type:'عطرية وحيوية',price:95,tag:'aromatic',badge:'للتاكو والشوربة',image:'https://images.unsplash.com/photo-1516865135108-6b9489a0f07f?auto=format&fit=crop&w=700&q=80'},
  {id:'dill',name:'شبت',type:'نكهة عطرية ناعمة',price:95,tag:'aromatic',badge:'للمأكولات البحرية',image:'https://images.unsplash.com/photo-1620637572417-1dd62313ee41?auto=format&fit=crop&w=700&q=80'},
  {id:'amaranth',name:'أمارانث أحمر',type:'لمسة ترابية بلون ياقوتي',price:110,tag:'colorful',badge:'اختيار الشيف',image:'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=700&q=80'},
  {id:'beet',name:'شمندر',type:'حلو ولونه عميق',price:100,tag:'colorful',badge:'للتزيين',image:'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?auto=format&fit=crop&w=700&q=80'},
  {id:'mizuna',name:'ميزونا ياباني',type:'خردلي خفيف ومسنن',price:90,tag:'spicy',badge:'آسيوي',image:'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=700&q=80'},
  {id:'watercress',name:'حب الرشاد',type:'حار ومنعش',price:85,tag:'spicy',badge:'نكهة قوية',image:'https://images.unsplash.com/photo-1628773822503-930a7eaecf80?auto=format&fit=crop&w=700&q=80'},
  {id:'bok-choy',name:'بوك تشوي',type:'مقرمش ونظيف الطعم',price:80,tag:'mild',badge:'للستير فراي',image:'https://images.unsplash.com/photo-1531171585559-33d1b4eec2c5?auto=format&fit=crop&w=700&q=80'},
  {id:'wheatgrass',name:'عشب القمح',type:'جرعة خضراء مركزة',price:65,tag:'popular',badge:'للعصائر',image:'https://images.unsplash.com/photo-1591863598823-7f47e7f04c21?auto=format&fit=crop&w=700&q=80'},
  {id:'chef-mix',name:'مزيج الشيف',type:'5 نكهات في علبة واحدة',price:120,tag:'popular',badge:'اختيار الشيف',image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=700&q=80'},
  {id:'rainbow-mix',name:'مزيج قوس قزح',type:'جرجير وفجل وكرنب وأمارانث',price:125,tag:'popular',badge:'هدية مثالية',image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=700&q=80'}
];
const englishNames = {sunflower:'SUNFLOWER SHOOTS',radish:'RED RADISH',broccoli:'BROCCOLI',arugula:'ARUGULA',pea:'PEA SHOOTS','red-cabbage':'RED CABBAGE',kale:'RUSSIAN KALE',mustard:'RED MUSTARD',kohlrabi:'PURPLE KOHLRABI',basil:'ITALIAN BASIL',cilantro:'CILANTRO',dill:'DILL',amaranth:'RED AMARANTH',beet:'BEET',mizuna:'MIZUNA',watercress:'WATERCRESS','bok-choy':'BOK CHOY',wheatgrass:'WHEATGRASS','chef-mix':"CHEF'S MIX",'rainbow-mix':'RAINBOW MIX'};
const localVisuals = {sunflower:'sunflower',radish:'spicy',broccoli:'green',arugula:'spicy',pea:'green','red-cabbage':'purple',kale:'green',mustard:'spicy',kohlrabi:'purple',basil:'herb',cilantro:'herb',dill:'herb',amaranth:'purple',beet:'purple',mizuna:'spicy',watercress:'spicy','bok-choy':'green',wheatgrass:'green','chef-mix':'mix','rainbow-mix':'mix'};
const productImage = product => `assets/${localVisuals[product.id] || 'mix'}.svg`;
let cart = JSON.parse(localStorage.getItem('vitagreen-cart') || '[]');
let currentFilter = 'all';
const grid = document.querySelector('#productGrid');
const cartDrawer = document.querySelector('#cartDrawer');
const overlay = document.querySelector('#overlay');
const fmt = n => `${n.toLocaleString('ar-EG')} ج.م`;

function productCard(p){return `<article class="product-card"><div class="product-image"><img src="${productImage(p)}" alt="ميكروجرين ${p.name}" loading="lazy"/><span class="badge">${p.badge}</span><button class="fav" aria-label="حفظ ${p.name}" data-favorite="${p.id}"><i data-lucide="heart"></i></button></div><div class="product-info"><small class="product-en">${englishNames[p.id]}</small><h3>${p.name}</h3><small>${p.type}</small><div class="product-bottom"><span class="price">${fmt(p.price)} <small>/ علبة</small></span><button class="add-btn" data-add="${p.id}" aria-label="أضف ${p.name}"><i data-lucide="plus"></i></button></div></div></article>`}
function renderProducts(){let set=products.filter(p=>currentFilter==='all'||p.tag===currentFilter);grid.innerHTML=set.map(productCard).join('');lucide.createIcons();}
function save(){localStorage.setItem('vitagreen-cart',JSON.stringify(cart));}
function addToCart(id){let existing=cart.find(x=>x.id===id);if(existing)existing.qty++;else cart.push({...products.find(p=>p.id===id),qty:1});save();renderCart();toast('أضفنا الحصاد إلى سلتك');}
function renderCart(){const items=document.querySelector('#cartItems'), footer=document.querySelector('#cartFooter');const count=cart.reduce((n,x)=>n+x.qty,0);document.querySelectorAll('.cart-count').forEach(el=>el.textContent=count);if(!cart.length){items.innerHTML='<div class="empty-cart"><i data-lucide="shopping-bag"></i><p>سلتك تنتظر حصادًا طازجًا.</p><a href="#shop" class="button primary close-cart">ابدأ التسوق</a></div>';footer.hidden=true}else{items.innerHTML=cart.map(x=>`<div class="cart-line"><img src="${productImage(x)}" alt="${x.name}"/><div><h4>${x.name}</h4><b>${fmt(x.price)}</b><div class="quantity"><button data-qty="${x.id}" data-change="1">+</button><span>${x.qty}</span><button data-qty="${x.id}" data-change="-1">−</button></div></div><button class="remove" data-remove="${x.id}" aria-label="حذف"><i data-lucide="trash-2"></i></button></div>`).join('');footer.hidden=false;document.querySelector('#cartTotal').textContent=fmt(cart.reduce((n,x)=>n+x.price*x.qty,0));}lucide.createIcons();}
function toggleCart(open){cartDrawer.classList.toggle('open',open);overlay.classList.toggle('show',open);document.body.style.overflow=open?'hidden':'';}
let toastTimer;function toast(message){const el=document.querySelector('#toast');el.querySelector('span').textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)addToCart(add.dataset.add);const filter=e.target.closest('[data-filter]');if(filter){currentFilter=filter.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===filter));renderProducts()}const fav=e.target.closest('[data-favorite]');if(fav){fav.classList.toggle('active');toast(fav.classList.contains('active')?'حُفظ في المفضلة':'أزيل من المفضلة')}const q=e.target.closest('[data-qty]');if(q){const item=cart.find(x=>x.id===q.dataset.qty);item.qty+=Number(q.dataset.change);if(item.qty<1)cart=cart.filter(x=>x.id!==item.id);save();renderCart()}const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(x=>x.id!==remove.dataset.remove);save();renderCart();toast('تم حذف المنتج من السلة')}if(e.target.closest('#cartTrigger'))toggleCart(true);if(e.target.closest('.close-cart')||e.target===overlay)toggleCart(false);if(e.target.closest('#checkoutBtn')){if(cart.length){toast('تم تجهيز طلبك — سنفتح واتساب لتأكيد التفاصيل');setTimeout(()=>window.open('https://wa.me/201000000000?text='+encodeURIComponent('مرحبًا، أريد تأكيد طلبي من فيتا جرين بقيمة '+document.querySelector('#cartTotal').textContent),'_blank'),500)}}});
document.querySelector('.search-toggle').addEventListener('click',()=>{document.querySelector('#searchPanel').classList.add('open');setTimeout(()=>document.querySelector('#searchInput').focus(),200)});document.querySelector('.close-search').addEventListener('click',()=>document.querySelector('#searchPanel').classList.remove('open'));document.querySelector('#searchInput').addEventListener('input',e=>{const q=e.target.value.trim();grid.innerHTML=products.filter(p=>p.name.includes(q)||p.type.includes(q)).map(productCard).join('');lucide.createIcons()});document.querySelector('#menuTrigger').addEventListener('click',()=>document.querySelector('#mobileNav').classList.toggle('open'));document.querySelectorAll('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('#mobileNav').classList.remove('open')));document.querySelector('#subscriptionBtn').addEventListener('click',()=>toast('رائع! سنفتح قريبًا خطوات اختيار اشتراكك.'));document.querySelector('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();e.target.reset();toast('أهلًا بك! كود خصمك: GREEN10')});document.querySelector('#showAll').addEventListener('click',e=>{e.preventDefault();currentFilter='all';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderProducts();document.querySelector('#shop').scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('img').forEach(img=>{const fallback=()=>{img.onerror=null;img.src='assets/mix.svg'};img.addEventListener('error',fallback);if(img.complete&&!img.naturalWidth)fallback()});document.querySelectorAll('.reveal').forEach(el=>new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12}).observe(el));renderProducts();renderCart();lucide.createIcons();
